### ISSUE TITLE
How Is This Structured?

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/alef#1]
I am just wondering on how exactly this is structured. In the stage 1 draft, in the examples, I see an `App.alef.jsx`, an `App.js`, and an `index.html`. I get that `App.alef.jsx` is the alef component, so is `App.js` the compiled output? If so, is `helpers.js` just to make it a little easier to read as a draft because I believe one of the core features was to be only a compiler and not have a runtime library.

**Comment by ije** [comment]
yes, `App.js` is the output of compiler, and `helpers.js` will be as a library shared in component outputs not only in *DRAFT*. Of course we can insert **helpers** or use native DOM method in each component js, but please consider a real application may have many components, the `helpers.js` is useful to reduce final bundle size of the app. I mean not like React/Vue runtime, the `helpers.js` just a collection of help functions.

**Comment by shadowtime2000** [comment]
@ije Would the compiler automatically use the `helpers.ts`?

**Comment by ije** [comment]
@shadowtime2000 sure, will import it by usage
